apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_backend.name }}
spec:
  selector:
    app: {{ .Values.service_backend.label }}
  ports:
  - port: 6379
    targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_frontend.name }}
spec:
  selector:
    app: {{ .Values.service_frontend.label }}
  type: {{ .Values.service_lb.type }}
  ports:
  - port: {{ .Values.service_lb.port }}
    targetPort: {{ .Values.service_lb.targetPort }}
    nodePort: {{ .Values.service_lb.nodePort }}
